# Generated by Django 4.0.5 on 2022-07-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0007_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=30)),
                ('cantidad_salas', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Estudios',
            },
        ),
    ]
