# Generated by Django 4.0.5 on 2022-07-24 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0008_detalleestudios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleEstudios',
        ),
    ]
