# Generated by Django 4.0.5 on 2022-07-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0009_delete_detalleestudios'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudios',
            name='detalle',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
