# Generated by Django 4.0.5 on 2022-07-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0010_estudios_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudios',
            name='imagen',
            field=models.ImageField(default='imagen', upload_to=''),
        ),
        migrations.AlterField(
            model_name='estudios',
            name='detalle',
            field=models.CharField(max_length=500),
        ),
    ]
