# Generated by Django 4.0.5 on 2022-07-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0011_estudios_imagen_alter_estudios_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='estudios/', verbose_name='Imagen'),
        ),
    ]
