# Generated by Django 4.0.5 on 2022-07-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0015_alter_estudios_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
